### ISSUE TITLE
`Audio thread died`.

### ISSUE THREAD

**Issue by kindaro** [fishfight/FishFight#119]
I have two laptops with different hardware but nearly identical software — Arch Linux. On the laptop №1 the game runs fine, but on the laptop №2 it has some sound problems.

<details>
<summary>See backtrace.</summary>

    % export RUST_BACKTRACE=full
    % cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.20s
    Running `target/debug/fishfight`
    thread '<unnamed>' panicked at 'Can't set rate.', /home/kindaro/.cargo/registry/src/github.com-1ecc6299db9ec823/quad-snd-0.2.2/src/alsa_snd.rs:54:9
    stack backtrace:
    0:     0x555b00baedc0 - std::backtrace_rs::backtrace::libunwind::trace::h930cf0be2ce43851
    at /build/rust/src/rustc-1.54.0-src/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
    1:     0x555b00baedc0 - std::backtrace_rs::backtrace::trace_unsynchronized::he8c90b95546147bf
    at /build/rust/src/rustc-1.54.0-src/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
    2:     0x555b00baedc0 - std::sys_common::backtrace::_print_fmt::h2d518076e7529961
    at /build/rust/src/rustc-1.54.0-src/library/std/src/sys_common/backtrace.rs:67:5
    3:     0x555b00baedc0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc03afe5108b924f5
    at /build/rust/src/rustc-1.54.0-src/library/std/src/sys_common/backtrace.rs:46:22
    4:     0x555b00bd057c - core::fmt::write::h03501fd186e1f342
    at /build/rust/src/rustc-1.54.0-src/library/core/src/fmt/mod.rs:1110:17
    5:     0x555b00ba9225 - std::io::Write::write_fmt::he6bd3203a99cf841
    at /build/rust/src/rustc-1.54.0-src/library/std/src/io/mod.rs:1588:15
    6:     0x555b00bb0d8b - std::sys_common::backtrace::_print::h6d8d274cdb4b9345
    at /build/rust/src/rustc-1.54.0-src/library/std/src/sys_common/backtrace.rs:49:5
    7:     0x555b00bb0d8b - std::sys_common::backtrace::print::hdbba7107ed5db727
    at /build/rust/src/rustc-1.54.0-src/library/std/src/sys_common/backtrace.rs:36:9
    8:     0x555b00bb0d8b - std::panicking::default_hook::{{closure}}::h69616457d96cfc5a
    at /build/rust/src/rustc-1.54.0-src/library/std/src/panicking.rs:208:50
    9:     0x555b00bb0861 - std::panicking::default_hook::h10bbc125f6ee1853
    at /build/rust/src/rustc-1.54.0-src/library/std/src/panicking.rs:225:9
    10:     0x555b00bb1464 - std::panicking::rust_panic_with_hook::h6eb033573a515ade
    at /build/rust/src/rustc-1.54.0-src/library/std/src/panicking.rs:622:17
    11:     0x555b00b62974 - std::panicking::begin_panic::{{closure}}::h65c57f58059ea8de
    at /build/rust/src/rustc-1.54.0-src/library/std/src/panicking.rs:542:9
    12:     0x555b00b627bc - std::sys_common::backtrace::__rust_end_short_backtrace::h746ac89937dea4ce
    at /build/rust/src/rustc-1.54.0-src/library/std/src/sys_common/backtrace.rs:141:18
    13:     0x555b009b07ac - std::panicking::begin_panic::h270725cfc9587c4d
    at /build/rust/src/rustc-1.54.0-src/library/std/src/panicking.rs:541:12
    14:     0x555b00b5f60c - quad_snd::snd::setup_pcm_device::h08b37f8cb4bab291
    at /home/kindaro/.cargo/registry/src/github.com-1ecc6299db9ec823/quad-snd-0.2.2/src/alsa_snd.rs:54:9
    15:     0x555b00b5f60c - quad_snd::snd::audio_thread::hcd9d245f20df7ed5
    at /home/kindaro/.cargo/registry/src/github.com-1ecc6299db9ec823/quad-snd-0.2.2/src/alsa_snd.rs:101:22
    16:     0x555b00b62804 - quad_snd::snd::AudioContext::new::{{closure}}::h49ee68f5b0d82888
    at /home/kindaro/.cargo/registry/src/github.com-1ecc6299db9ec823/quad-snd-0.2.2/src/alsa_snd.rs:152:13
    17:     0x555b00b62804 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha4910be306093841
    at /build/rust/src/rustc-1.54.0-src/library/std/src/sys_common/backtrace.rs:125:18
    18:     0x555b00b607eb - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h7bf2f5a18552903a
    at /build/rust/src/rustc-1.54.0-src/library/std/src/thread/mod.rs:481:17
    19:     0x555b00b607eb - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h1c5520255c16006f
    at /build/rust/src/rustc-1.54.0-src/library/std/src/panic.rs:347:9
    20:     0x555b00b607eb - std::panicking::try::do_call::h9f9747d23dc8fce2
    at /build/rust/src/rustc-1.54.0-src/library/std/src/panicking.rs:401:40
    21:     0x555b00b607eb - std::panicking::try::h4e1c3bcecbeb55eb
    at /build/rust/src/rustc-1.54.0-src/library/std/src/panicking.rs:365:19
    22:     0x555b00b607eb - std::panic::catch_unwind::h6eb715a1a1e27846
    at /build/rust/src/rustc-1.54.0-src/library/std/src/panic.rs:434:14
    23:     0x555b00b607eb - std::thread::Builder::spawn_unchecked::{{closure}}::h1f3c632a0c1e06b9
    at /build/rust/src/rustc-1.54.0-src/library/std/src/thread/mod.rs:480:30
    24:     0x555b00b607eb - core::ops::function::FnOnce::call_once{{vtable.shim}}::h1c92d14966cdbae2
    at /build/rust/src/rustc-1.54.0-src/library/core/src/ops/function.rs:227:5
    25:     0x555b00bb4d07 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h3cbd4244f09edcd9
    at /build/rust/src/rustc-1.54.0-src/library/alloc/src/boxed.rs:1575:9
    26:     0x555b00bb4d07 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h041107f6fd35708c
    at /build/rust/src/rustc-1.54.0-src/library/alloc/src/boxed.rs:1575:9
    27:     0x555b00bb4d07 - std::sys::unix::thread::Thread::new::thread_start::h4934a766967bcd21
    at /build/rust/src/rustc-1.54.0-src/library/std/src/sys/unix/thread.rs:71:17
    28:     0x7f6d6716c259 - start_thread
    29:     0x7f6d66f485e3 - __GI___clone
    30:                0x0 - <unknown>
    Audio thread died
    Audio thread died
    Audio thread died
    Audio thread died
    Audio thread died
    Audio thread died
    Audio thread died
    Audio thread died
    Audio thread died
    Audio thread died
    Audio thread died

</details>

Let me know if there is some other information I should provide.

**Comment by olefasting** [comment]
This should probably be reported as an issue with Macroquad. I'm closing this, as it hasn't been reproduced
