### ISSUE TITLE
Pressing media keys on keyboard crashes the game on Linux

### ISSUE THREAD

**Issue by PotatoTech** [fishfight/FishFight#122]
Pressing any of the media keys (volume up/down, play/pause, etc.) on my keyboard crashes the game. The media keys seem to be mapped to their own evdev device, and Fish Fight detects that device as a gamepad.

Environment: Arch Linux 5.14.7, Xfce with Xorg

**Comment by olefasting** [comment]
This does not happen for me on Gnome w. Wayland. A heads up when it comes to Gilrs: It is using very strange mappings on the controllers I have tried it with (common ones, like 8bitdo), so it is probably wise to include some way of remapping, either by menu or, at the very least, a config file....

**Comment by PotatoTech** [comment]
I noticed the mapping issue with Nintendo-style controllers and noted it in the pull request. Are your controllers behaving as if they were Xbox controllers (A/B swapped and X/Y swapped), or is it some other layout?

As for remapping, it is a feature that I want as well, but should that be added in a separate PR?

**Comment by olefasting** [comment]
I got some very weitd mappings, with triggers (should be analog, I believe) mapped to press on the thumbsticks etc....

**Comment by PotatoTech** [comment]
The [existing code](https://github.com/fishfight/FishFight/blob/e7255ddf6f48bd4995a342d8c2872080d348626a/src/gui/main_menu.rs#L366-L380) using `quad-gamepad` already maps both the bumpers and thumbstick presses to switch tabs in the main menu. I am not aware of any other location where the game uses these inputs. Also, we should move this discussion to the PR.
