### ISSUE TITLE
Automate GitHub releases

### ISSUE THREAD

**Issue by orhun** [fishfight/FishFight#128]
Currently, there is no CD workflow for automating the release of tarballs/binaries on [GitHub releases page](https://github.com/fishfight/FishFight/releases). It would be nice to have this since it makes the whole release cycle easier by making it possible to release a new version by just pushing/creating a tag.

**Comment by emhagman** [comment]
I'd be happy to tackle this if we're okay using Github Actions! I believe they're free for open source software. I'm new to Rust but have a lot of CI/CD experience so this might be a good thing to start with.

**Comment by erlend-sh** [comment]
Nice, go ahead! 👍

**Comment by Animeshz** [comment]
Is he working on it? He doesn't seem to have any fork in his profile.

Can I take this?
