### ISSUE TITLE
Players can kill themselves with a sword throw

### ISSUE THREAD

**Issue by orhun** [fishfight/FishFight#142]
![rec_20211001T152016](https://user-images.githubusercontent.com/24392180/135619149-ce3550a2-ed5a-4d33-a9c0-9fdee4da907f.gif)

I don't know if this is a bug or feature but it seems a bit odd.

**To reproduce**: press `pick/drop` quickly while on air

If this is an issue, I'm happy to fix it with a little guidance :) If not, feel free to close it.

**Comment by erlend-sh** [comment]
It should be possible to self-pwn with a thrown sword, for example if it ricochets via the wall. But the interaction you’re demonstrating shouldn’t exist.

**Comment by orhun** [comment]
Then it looks like it is a _bug_ that occurs when the player sequentially picks and throws the sword mid-air. So defining a "grace time" for pick-drop sequence if the player drops the weapon while "not on ground" would solve the issue?

In fact, I just implemented this (with the grace time of 0.30) and it seems to fix it:

![rec_20211001T171826](https://user-images.githubusercontent.com/24392180/135635734-18dafacd-2502-49c6-8d50-64feee1299b7.gif)

**Comment by erlend-sh** [comment]
Excellent, sounds like a useful PR!
