### ISSUE TITLE
[SPEC] Blunderbuss & BlunderBass

### ISSUE THREAD

**Issue by SirGiraffey** [fishfight/FishFight#152]
![blunderbass and blunderbass](https://user-images.githubusercontent.com/57463655/135750130-6c3d0bab-7093-45b8-b842-fe6b8abcae07.png)

**Comment by erlend-sh** [comment]
We've got the art completed for this by @BumbertFiddlesticks:

#### Blunderbuss (remix of gun)
![image](https://user-images.githubusercontent.com/583842/140936896-c2a66c47-9ca4-4eef-b41d-468941938dd4.png)

#### Blunderbass

![image](https://user-images.githubusercontent.com/583842/140936946-105e958e-d4a9-4b24-932a-6672a4af5ad0.png)

Only the coding part of the task remains.

**Comment by SirGiraffey** [comment]
Love the design, although the stock and the fish tail don't look right. Maybe, as you said, remove the tail altogether or turn the tail into the stock of the gun

**Comment by billyb2** [comment]
If it's alright, I'd like to try to work on this issue

**Comment by BumbertFiddlesticks** [comment]
I'm not working on this anymore, but the blunderbass above isn't the final version! Not sure how .zip friendly github is but you can see final here: [Blunderbuss +BlunderBass.zip](https://github.com/fishfight/FishFight/files/7571727/Blunderbuss.%2BBlunderBass.zip)

If you still want to improve it, that's fine too of course, and best of luck with the project :)

**Comment by billyb2** [comment]
@BumbertFiddlesticks the art looks great! Thank you very much!!!
