### ISSUE TITLE
[SPEC] Starfish Launcher

### ISSUE THREAD

**Issue by SirGiraffey** [fishfight/FishFight#154]
![Starfish launcher](https://user-images.githubusercontent.com/57463655/135750161-86f2fd17-18c4-48f6-a637-2b9071c8f719.png)

**Comment by zicklag** [comment]
Is it right that the starfish shot out of the launcher should despawn when colliding with fish, instead of sticking around like the throwable starfish? That way the starfish launcher can only cause an accumulation of throwable starfish on the course if players keep catching them.

**Comment by SirGiraffey** [comment]
Yeah, you're probably right, but maybe these uncatchable starfish should have a different color, like red for example

**Comment by zicklag** [comment]
Well, I think they can all be catchable, the only difference would be that the ones shot out of the launcher wouldn't automatically drop normal starfish after colliding with a fish.

So the only way to accumulate more starfish on the course would be to catch them out of mid-air from a launcher.

**Comment by SirGiraffey** [comment]
Sounds good!

**Comment by zicklag** [comment]
This can be closed now. It was implemented in #422.
