### ISSUE TITLE
gpu driver crash

### ISSUE THREAD

**Issue by lenscas** [fishfight/FishFight#162]
Found a way for FishFight to crash my laptop. Just use the arrow keys to select Network, RT and that seems to crash my GPU driver. (Screen freezes and eventually goes black, while music which comes from youtube keeps working).

System info (copied from what hardinfo told me)

OS:
Kernel | Linux 5.4.150-1-MANJARO (x86_64)
Version | #1 SMP PREEMPT Thu Sep 30 16:13:54 UTC 2021
C Library | GNU C Library / (GNU libc) 2.33
Distribution | Manjaro Linux

Computer:
Processor | AMD Ryzen 7 2700U with Radeon Vega Mobile Gfx
Memory | 7079MB (3353MB used)
Machine Type | Notebook
Operating System | Manjaro Linux
User Name | lenscas (Lenscas)
Date/Time | zo 10 okt 2021 14:24:15 CEST

Display:
Resolution | 1920x1080 pixels
OpenGL Renderer | AMD Radeon(TM) Vega 3 Graphics (RAVEN, DRM 3.35.0, 5.4.150-1-MANJARO, LLVM 12.0.1)
Session Display Server | [X11] The X.Org Foundation 12013000

OpenGL (GLX):
Vendor | AMD
Renderer | AMD Radeon(TM) Vega 3 Graphics (RAVEN, DRM 3.35.0, 5.4.150-1-MANJARO, LLVM 12.0.1)
Direct Rendering | Yes
Version (Compatibility) | 4.6 (Compatibility Profile) Mesa 21.2.3
Shading Language Version (Compatibility) | 4.60
Version (Core) | 4.6 (Core Profile) Mesa 21.2.3
Shading Language Version (Core) | 4.60
Version (ES) | OpenGL ES 3.2 Mesa 21.2.3
Shading Language Version (ES) | OpenGL ES GLSL ES 3.20
GLX Version | 1.4

I'm not sure what logs to look at (if any). So, feel free to tell me where I can find relevant logs :)

**Comment by olefasting** [comment]
Confirmed, but I only get it when going to Local Game and pressing LT to cycle to last tab index...
I have similar specs as the author (Ryzen 5/Vega 8)

**Comment by olefasting** [comment]
I didn't really look into the error message, but I checked that it wasn't a simple index out of bounds error, so my guess is that this is a bug in Macroquad, not in our code....

**Comment by lenscas** [comment]
> I didn't really look into the error message, but I checked that it wasn't a simple index out of bounds error, so my guess is that this is a bug in Macroquad, not in our code....

what error message? What log? For me the laptop just dies so not sure what to look at to find out what breaks...

**Comment by lenscas** [comment]
so.. for you only the game dies?

Then I wonder if it is the same bug, or if it is the same bug what prevents the entire computer from crashing in your case.

**Comment by olefasting** [comment]
Also, there probably are differences in how things are handled between us, as we have different Vega APUs. What crashes the driver in one case, doesn't necessarily do so in the other case...

**Comment by lenscas** [comment]
you have a different bug. If I go left, the game crashes for me as well rather than my driver.
That problem is caused by the line https://github.com/fishfight/FishFight/blob/50b491e9f0fbc85439547c3a443cd09b74fc387e/src/gui/main_menu.rs#L446

the index is set to `MODE_SELECTION_TAB_COUNT` (which is 3) however, in the match it is 0 indexed, so the index 2 is the highest that is being checked for.

Simply adding a `- 1` to that line _should_ fix it. However, I can't really test this as that will probably result in my laptop crashing again :(

**Comment by olefasting** [comment]
Yeah, you are right, of course. I read the `No mapping for...` as the error. The error I got is my fault, actually, so I'll fix that....

**Comment by olefasting** [comment]
Do you also have a /dev/input/js0, even when no gamepad is connected? This has been a problem for me, when using gamepad-rs with FishFight, with both my new and my old laptop. This (linux registering touchpad as a joypad) might be the explanation for that, then

**Comment by olefasting** [comment]
I'm closing this. We can reopen it if the is still an issue

**Comment by lenscas** [comment]
yea, sorry for taking so long to check. Busy with other stuff.

I also doubt it would NOT be fixed by the removal of that screen. As far as I know, that screen was the only one that caused the crash and I fail to see how removing that screen would NOT result in that crash being removed.

**Comment by olefasting** [comment]
Then it is the same error I had. It was connected to the network implementation. Unsure why it leads to a gpu driver crash, though

**Comment by lenscas** [comment]
Perhaps it is something else that crashes and it just looks like a GPU driver crash?

All I had to go on was "screen goes black, music keeps playing" which to me sounds like a GPU crash but might just be something else.

**Comment by olefasting** [comment]
Ah, ok. I thought you had it from logs, or something. Then it is probably the network implementations fault, as I have it pinned down to the update of the connection state. That is not going to be used, as we are going to use steam in stead, so I guess the mystery is solved :)
