### ISSUE TITLE
[Editor] Tool Icons

### ISSUE THREAD

**Issue by olefasting** [fishfight/FishFight#167]
We need icons for all the common tools in the editor.

The files should be 128x128px (they will be scaled down to around ~~48x48~~ 64x64, so you should probably work in this size and scale up, if you are creating pixel art)

A list of tools would include (but is not limited to):

- Place tile
- Place object
- Eraser
- Select object
- Marquee select objects

More tools than this are likely to be added, as contributions start to roll in...

**Comment by erlend-sh** [comment]
We’ve got an initial bunch of icons in. Will be adding new ones on demand.

![5EB4A24B-8180-41A5-8C2A-FD92329A4F40](https://user-images.githubusercontent.com/583842/146561771-d2ea51b9-bd9c-4527-afdf-abd27e8c7ddd.png)
![7A539D4B-827C-47B6-B6F1-F4537ED2D2CF](https://user-images.githubusercontent.com/583842/146561776-4edee116-3bf9-4dfd-ab40-9311e371caac.jpeg)
