### ISSUE TITLE
Create style guide (naming conventions etc)

### ISSUE THREAD

**Issue by olefasting** [fishfight/FishFight#186]
Currently I am refactoring the item system and I have come across a lot of loose naming conventions from our prototyping days.

I have corrected some of them as I go, like `facing` on `PhysicsBody`, now, renamed `is_facing_right`. I am unsure how many times I have had to double check whether this means that the body is facing left or right while working on this project...

So, I propose that we create some naming conventions to supplement the other style enforcement put in place by `Clippy`.

In general, names should be informative and it should be possible to read the purpose of a variable from its name and its immediate context. This means that members and other variables that hold a value like, say, recoil should be named recoil. They should also not be specific to a subset of the functionality they will apply to. This is not that big of an issue but `shoot_coroutine` should, for example, in stead be named `attack_coroutine`, as it will also apply in the case of melee weapons...

If getters and setters are implemented, they should be prefixed as `get_some_value` and `set_some_value`. This convention should be used, whether the methods are getting or setting an actual (private) member var `some_value` or a set of member values.

I also think we should stick to naming `bool` variables and members using verbs, like `is_doing_something` or `is_using_something`, in the case of vars and member vars, or `should_use_something`  and so on, in the case of arguments (in the case of non-member functions, it might fit better to use `is_[...]` for arguments, but you get the idea...)

These are my proposals. Feel free to add to these or to give any criticism or feedback, if you have it!

**Comment by PotatoTech** [comment]
The [Rust API Guidelines](https://rust-lang.github.io/api-guidelines/naming.html#getter-names-follow-rust-convention-c-getter) recommends against using the `get_` prefix. These guidelines are meant for public APIs however, so we should pick whatever makes the codebase easier to navigate. I agree with the rest of the proposals.

**Comment by olefasting** [comment]
My reason for always going for the prefixes are that they avoid shadowing/conflicts with member names. It is not a hard requirement from my side, so I am fine with sticking to the style guide, if that is what people want. I am a bit stumped by this, though, as I see this naming convention, all over the place, including in the std (get_[..] and try_get_[..]). I would still propose that we use it, as it increases readability and eases navigation of the code, in my opinion, but I will, of course, bend to the will of the majority here :)
