### ISSUE TITLE
Level Editor MVP

### ISSUE THREAD

**Issue by erlend-sh** [fishfight/FishFight#26]
We eventually want to let players create new levels from within the game itself, rather than having to open .json maps in Tiled. Our own level editor should support all of the basics we can currently do with Tiled, plus a few more conveniences added on top.

References:
![image](https://user-images.githubusercontent.com/583842/126869114-974f7c8d-6fe4-4421-858f-85750a5a22c6.png)

https://steamcommunity.com/sharedfiles/filedetails/?id=1305733533
https://duckgame.fandom.com/wiki/Level_editor

Level editor should let a modder:
- Create a new map
- Save the current map
- Load a map
- Play the current map

Convenience features will include:
- [Autotiling](https://doc.mapeditor.org/en/stable/manual/automapping/)
- ??

Later:
- [Procedural maps](https://www.notion.so/erlendsh/Procedural-maps-e2a2d61f77b0441f8a20b8c778e608d1).
- Upload map to FF Hub.
- Change the grid size of the background (8x8, 16x16, or 32x32)
- ??

---

Prior art:

https://github.com/brooks-builds/platformer_with_level_editor
https://www.twitch.tv/collections/QZm7Miz_fxbNCw

**Comment by olefasting** [comment]
I'm currently working on a proposal for this
