### ISSUE TITLE
Improve local game setup screen(s)

### ISSUE THREAD

**Issue by olefasting** [fishfight/FishFight#300]
We should improve the local game setup screen to enable more players in local games.

Currently we are advertising 2-4 players but this isn't really a limitation that we need to adhere to. Obviously, we can not have more than two players using the keyboard at one time, but there is nothing that binds us to the number four, if there are enough gamepads connected...
For starters, though, we should design and implement a game setup process that can accommodate more than one player. I was thinking that we remove the first screen that collect input and sets input scheme and in stead just jump directly to what is today the character selection screen. Here, we can add one character selection panel for each player that is added by pressing some button either on the keyboard or a connected controller. When two or more players are connected and have a character selected, the option to start the game should appear.
We should also upgrade the character selection screen to display a flexible grid, scaling and stacking the individual character selection panels according to count (like has been done for the map selection screen, only without pagination).

**Comment by erlend-sh** [comment]
Yeah, on local we can allow 8 players. We probably won’t design levels for that any time soon though. Might even leave that entirely to the modding community, since it’s a bit far removed from the default, core game experience of 2-4 players.

**Comment by olefasting** [comment]
> Yeah, on local we can allow 8 players. We probably won’t design levels for that any time soon though. Might even leave that entirely to the modding community, since it’s a bit far removed from the default, core game experience of 2-4 players.

Yeah, I could probably add a `players` parameters to `Map` that can be set in editor (and take a default based on size, if not) that can be used to show recommended player count for the individual maps. Then we can just have our core maps be 1-4 and let it be up to users to create maps for more players

**Comment by tigleym** [comment]
> For starters, though, we should design and implement a game setup process that can accommodate more than one player. I was thinking that we remove the first screen that collect input and sets input scheme and in stead just jump directly to what is today the character selection screen. 

I think this makes sense. I feel like collecting input and setting an input scheme would happen _during_ the character selection phase. 

> Here, we can add one character selection panel for each player that is added by pressing some button either on the keyboard or a connected controller.

Perhaps we could include messaging somewhere saying **Press Enter to Join**? 

 > When two or more players are connected and have a character selected, the option to start the game should appear. We should also upgrade the character selection screen to display a flexible grid, scaling and stacking the individual character selection panels according to count (like has been done for the map selection screen, only without pagination).

Maybe we could play around with "character selection" designs where we display a roster of all the available characters for players to choose from? Then we'd display a grid beneath this roster showing connected players + the characters they've chosen. 

This is very much inspired from the character selection screen for Super Smash Bros. Ultimate though and perhaps this adds more noise to the UI than is necessary.

**Comment by olefasting** [comment]
> Perhaps we could include messaging somewhere saying Press Enter to Join?

This is, more or less how we do it now, only we have a screen before character selection that creates a player using whichever input method you press "confirm" on (`enter` for keyboard and `start` or `A` for gamepad). We will probably need to continue doing it like this but I think we should merge this part of the process into the character selection screen.

> Maybe we could play around with "character selection" designs where we display a roster of all the available characters for players to choose from? Then we'd display a grid beneath this roster showing connected players + the characters they've chosen.

This would definitely be cool but there are two things to keep in mind:

Firstly, there are no limitations to how many characters can be added to the game, by extending `player_characters.json`. This means that a roster screen will have to accommodate any amount of available characters...

Also, it seems like very few people are really interested in creating UI as it is currently a bit finicky and has a lot of overhead, due to the maturity of Macroquads UI library. This means that the time-investment needed to create good UI is rather big at the moment. I have worked with graphic design and layouts for many years, before I became a programmer, so I can definitely help with design and quality control but for the time being my main focus is diverted elsewhere....

If anyone want to tackle something like this, that would be awesome, though!

**Comment by erlend-sh** [comment]
The grid idea is a good v2 addition for our character selection 👍 It has to be figured out in conjunction with our modular character editor in #302 so this part of the discussion can be continued there with more mock-ups.

**Comment by tigleym** [comment]
> Also, it seems like very few people are really interested in creating UI as it is currently a bit finicky and has a lot of overhead, due to the maturity of Macroquads UI library. 

Ah yeah. I noticed there seems to be a lack of tutorial / "hands-on" docs for the UI library, which perhaps makes it a little intimidating. This might be a good area for the documentation/learning track to explore.

**Comment by olefasting** [comment]
I am closing this, for now, as we are taking a more overarching approach to reworking UI, in the mid- to long-term, as this will be part of migrating our normal game builds over on the new backend that is underway for our Ultimate build
