### ISSUE TITLE
Credits 

### ISSUE THREAD

**Issue by erlend-sh** [fishfight/FishFight#304]
List full proiect credits in-game, with credits music. A credits.md file will act as the data source for the in-game screen, although it’s totally fine if the data is imported entirely by hand, since it’s just a few dozen names and titles.

- [x] credits.md file
- [x] In-game credits

v2 of credits should incorporate #303

**Comment by tigleym** [comment]
@erlend-sh  Is there some sort of "end game" condition to trigger this scene? Or are we thinking about having a "Credits" main menu options that will take players to this?

**Comment by erlend-sh** [comment]
To start with let’s just add it to the main menu. The credits music is done :) I’ll share on Discord.

**Comment by erlend-sh** [comment]
I've completed the first take on the prerequisite `CREDITS.md` file. First draft of in-game credits screen is just a reprint of that file.
