### ISSUE TITLE
GLX Error

### ISSUE THREAD

**Issue by beucismis** [fishfight/FishFight#336]
Hi, I am getting this error while running the game.

```bash
[03:52 PM] [user@debian:~/Downloads]
$ ./fishfight 
GLX: failed to create GL context
```

OS: `Debian GNU/Linux bookworm/sid x86_64`
Kernel: `5.15.0-2-amd64`
GL Version: `2.1 Mesa 21.2.6`

**Comment by orhun** [comment]
Hello, game engine of Fish Fight ([macroquad](https://macroquad.rs/)) only supports `OpenGL 3.2+`. Related issues:
- https://github.com/not-fl3/macroquad/issues/67
- https://github.com/not-fl3/macroquad/issues/259

**Comment by beucismis** [comment]
Thanks.

**Comment by agahemir** [comment]
You can try `MESA_GL_VERSION_OVERRIDE=4.3 ./fishfight ` 

I don't know if it will work but it was working in another game.

**Comment by beucismis** [comment]
> You can try `MESA_GL_VERSION_OVERRIDE=4.3 ./fishfight `
> 
> I don't know if it will work but it was working in another game.

Thank you but it didn't work.
