### ISSUE TITLE
libSDL2 related error on MacOS when launching

### ISSUE THREAD

**Issue by Niceplace** [fishfight/FishFight#370]
Hi folks ! I just wanted to share a fix that I had to do to get the game working on my mac. I still have problems understanding how multiplayer over the network works but I will leave that for a separate issue.

Some system/tooling specs: 

I'm using 
- MacOS Monterey 12.1
- Homebrew 3.3.14
- `Rustup show` gives:
```
Default host: x86_64-apple-darwin
rustup home:  /Users/sbeaulieu/.rustup

installed targets for active toolchain
--------------------------------------

wasm32-unknown-unknown
x86_64-apple-darwin

active toolchain
----------------

stable-x86_64-apple-darwin (default)
rustc 1.58.1 (db9d1b20b 2022-01-20)
```
- Cargo version: 1.58.0 (f01b232bc 2022-01-19)

I built the game with the FishLauncher (a5594c7cb6478a312488f893c857f9f491ebdd9a on master). I can install & build fine but when I try to launch the game it I get the following:

```
dyld[41160]: Library not loaded: @rpath/libSDL2-2.0.dylib
  Referenced from: /Users/sbeaulieu/.fishfight/v0.4/fishfight
  Reason: tried: '/usr/local/lib/libSDL2-2.0.dylib' (no such file), '/usr/lib/libSDL2-2.0.dylib' (no such file)
```

Checking `/usr/local/lib` gives a quick response, apparently I have `libSDL2-2.0.0.dylib` but FishFight seems to be looking for `libSDL2-2.0.dylib`

```
 sbeaulieu  /usr/local/lib  ls -al /usr/local/lib/ | grep -i libSDL2
\lrwxr-xr-x    1 sbeaulieu  admin      45 18 Jan 23:13 libSDL2-2.0.0.dylib -> ../Cellar/sdl2/2.0.20/lib/libSDL2-2.0.0.dylib
lrwxr-xr-x    1 sbeaulieu  admin      35 18 Jan 23:13 libSDL2.a -> ../Cellar/sdl2/2.0.20/lib/libSDL2.a
lrwxr-xr-x    1 sbeaulieu  admin      39 18 Jan 23:13 libSDL2.dylib -> ../Cellar/sdl2/2.0.20/lib/libSDL2.dylib
lrwxr-xr-x    1 sbeaulieu  admin      40 18 Jan 23:13 libSDL2_test.a -> ../Cellar/sdl2/2.0.20/lib/libSDL2_test.a
lrwxr-xr-x    1 sbeaulieu  admin      39 18 Jan 23:13 libSDL2main.a -> ../Cellar/sdl2/2.0.20/lib/libSDL2main.a
```

A workaround was to add a second link without the extra `.0`

```
cd /usr/local/lib
ln -s ../Cellar/sdl2/2.0.20/lib/libSDL2-2.0.0.dylib libSDL2-2.0.dylib
```

Not sure if that's the best solution, I wonder if the naming is wrong because of Homebrew ? I didn't compare with Linux.
Anyways, just thought I would open this issue in case other folks run into the same problem, I can start the game just fine after applying my workaround but I'm wondering if there's a better solution.

Cheers :D !

**Comment by orhun** [comment]
Very interesting. I wonder if there is something we can do about it in our [release workflow](https://github.com/fishfight/FishFight/blob/main/.github/workflows/release.yml). I'll try to reproduce. (I blame Brew honestly 😄 )

Thanks for sharing the solution!

**Comment by orhun** [comment]
SDL2 is no longer a dependency for input handling so this workaround is not needed for the new versions.
