### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by throwaway1037** [fishfight/FishFight#408]
Are all files in the repo libre?

I ask because I found a PR which referenced an -NC license and I couldn't see a license on the license pack webpage.

**Comment by erlend-sh** [comment]
As our license file states:

> Fish Fight media assets are Copyright (c) 2020-2022 The Fish Fight Game Developers and licensed as [CC BY-NC](https://creativecommons.org/licenses/by-nc/4.0/).

https://spicylobster.itch.io/fish-world-pack

**Comment by throwaway1037** [comment]
Please may the proprietary data be released under a [libre](https://freedomdefined.org) license, as is the source code?

**Comment by erlend-sh** [comment]
We can’t do that, as proprietary platforms like Nintendo and Apple won’t let us publish our game with them if we don’t possess a minimum of ownership over our product.

It also prevents malicious actors from [duplicating the game in bad faith](https://www.gamesindustry.biz/articles/2022-02-17-clone-culture-and-its-continuous-impact-on-indie-devs). Unfortunately a baseline level of protection is necessary to operate within the current confines of the games market.

**Comment by throwaway1037** [comment]
Why is accepting the demands of unethical corporations more important than respecting the freedom of all the players of the game?

The concept of so-called "ownership" as you describe it makes no sense for published works because each user owns his or her copy, and really just amounts to the restriction of other people.

Why should everybody not have the freedom to effortlessly copy the game? The better games will win out over the poor ones by natural selection by users.

When you refer to so-called "protection", all this amounts to in practice is restriction on what people are allowed to to with copies of a work in their possession.

Moreover, why is the source code libre then? If the freedom of every user should be respected in source code, then why not in other data too?

I understand where you're coming from, but I'm sorry to say that you've bought into the propaganda of big game companies, the management of which which would rather die than respect the freedom of users of games their companies develop.

In the worst case scenario, why not release the data under multiple licenses in parallel, as is the code, to allow it both to be used in freedom and on proprietary platforms?

Thank you for responding so quickly. :)

**Comment by throwaway1037** [comment]
The article you linked is also heavily biased and presumes copying is a bad thing. If the games in question were libre, people wouldn't have to keep developing clones of them and could just copy and enjoy the original project.

**Comment by erlend-sh** [comment]
If you wanna go around demanding that all games should be 100% free in every way, please start with the AAA games that are 99.9% less open and free than ours. Better yet, build the future of games you wanna see for yourself, and leave everyone else to make art on their own terms.

We are being as open as we have deemed feasible to operate as a commercial, self-sustaining venture. The notion of an open yet commercial game (published on mainstream marketplaces) is largely unprecedented; there is no standard playbook on how to do this, so we have to proceed with some caution.

The license has been clarified, so I’ll close this discussion to prevent any further unnecessary debating.

**Comment by throwaway1037** [comment]
Thank you again for replying so quickly. :)

> If you wanna go around demanding that all games should be 100% free in every way, please start with the AAA games that are 99.9% less open and free than ours.

I don't want to have to beg and grovel at the feet of authors at all, but that reflects the sad state of affairs our current copyright system is in at the moment. You are correct, the games industry is far from freedom-respecting, but that's no excuse for us not to respect freedom.

Moreover, please see why ["open" misses the point of freedom](https://gnu.org/philosophy/open-source-misses-the-point.html).

> Better yet, build the future of games you wanna see for yourself,

I literally am not capable of this. The only people who can change the terms and conditions placed on published works are the copyright holders of the work, which is usually the inventor of the work. All I have the power to do is politely ask for the work to be liberated.

Liberating the entire games industry, which is "the future of games I want to see" would require a revolution in the way people think about freedom and ethics, and/or legislation outlawing proprietary works. Needless to say, we as a society are not there yet.

> and leave everyone else to make art on their own terms.

You frame this discussion as if I'm some sort of wrongdoer when in reality that title is awarded to the people who do not respect the freedom of others. I politely asked for the work to be liberated, just as the source code already is, because I thought this was an honest mistake, although it's looking more and more like you genuinely don't care about the freedom of others and would rather please multi-billion dollar games companies with a well-documented history of failing to respect the freedom and privacy of their paying customers.

> We are being as open as we have deemed feasible to operate as a commercial, self-sustaining venture.

You unfortunately made a miscalculation. Respecting freedom and commercialisation can easily go hand-in-hand. There are entire communities of people, such as the users of [Parabola](https://parabola.nu) who would be willing to purchase the game or otherwise contribute back to the project so long as it respects their freedom. However, they are going to remove FishFight from their repos instead because you refuse to grant freedom to people.

> The notion of an open yet commercial game (published on mainstream marketplaces) is largely unprecedented; there is no standard playbook on how to do this, so we have to proceed with some caution.

I understand the need for caution, although your game is not "open". -NC-type licenses are not "open source" and as such your game as a whole is proprietary, that is unless you also release the proprietary files under a libre license.

---

Again, I please ask that you release all files in freedom.

Thank you for reading this rather long reply. :)
