### ISSUE TITLE
Can Anybody Make this Jump?

### ISSUE THREAD

**Issue by zicklag** [fishfight/FishFight#428]
On level one I'm unable to make this jump:

![image](https://user-images.githubusercontent.com/25393315/169831818-f90aacd1-829d-4f70-9ac0-a056cd85a2ce.png)

I saw mentioned in #425 that the jump force wasn't high enough, but I've had this problem before the refactor, and after the revert.

I think the issue exists on most of the other levels, too, but I'd have to verify.

Is this maybe a regression from some time in the past where it was possible to jump that high?

I can look into fixing the jump height if that's the issue, I just wanted to make sure it was a physics issue and not a level design issue.

**Comment by erlend-sh** [comment]
Seems like more of a level issue to me. Jump height should be only slightly more than 2x the height of the unit, so that platform looks like it would be barely out of reach for an unassisted jump.

Needs an additional, lower platform, or a sproinger.

**Comment by zicklag** [comment]
Fixed in #434
