### ISSUE TITLE
Install & Play via `cargo run` fails with cannot find /usr/bin/ld: cannot find -lasound, -lGl, -lX11, -lXi

### ISSUE THREAD

**Issue by RyanNerd** [fishfight/FishFight#97]
`cargo run` 

churns for a bit and then fails to compile with this:

```
note: /usr/bin/ld: cannot find -lasound
          /usr/bin/ld: cannot find -lGL
          /usr/bin/ld: cannot find -lX11
          /usr/bin/ld: cannot find -lXi
          collect2: error: ld returned 1 exit status
```

**Comment by not-fl3** [comment]
Yes, you need to install said libraries. 

```
apt install pkg-config libx11-dev libxi-dev libgl1-mesa-dev libasound2-dev
```

(dependning on the disctro the exact command may vary)

**Comment by RyanNerd** [comment]
@not-fl3 Figured it out from a StackOverflow answer that clued me in: https://stackoverflow.com/a/17580157/4323201
I needed to create a soft link for each missing libXXXX.so

```bash
➜ locate libasound.so
/usr/lib/x86_64-linux-gnu/libasound.so.2
/usr/lib/x86_64-linux-gnu/libasound.so.2.0.0

➜ cd /usr/lib/x86_64-linux-gnu

# create a soft link for each missing libXXX.so:
➜ ln -s libsound.so.2 libsound.so

➜ ll libX11*
lrwxrwxrwx 1 root root   15 May 19 11:07 libX11.so.6 -> libX11.so.6.3.0
-rw-r--r-- 1 root root 1.3M May 19 11:07 libX11.so.6.3.0

➜ ln -s libX11.so.6 libX11.so
```

**Comment by not-fl3** [comment]
It really depends on the distro, but some of them (ubuntu) contains lib*.so only in -dev packages. Usually installing -dev pacakges helps without doing symlinks yourself.

**Comment by RyanNerd** [comment]
> It really depends on the distro, but some of them (ubuntu) contains lib*.so only in -dev packages. Usually installing -dev pacakges helps without doing symlinks yourself.

I'm running Linux Mint 20.2.
I tried installing the *-dev packages without success. It's up and running now. Thanks for your time and input.
