### ISSUE TITLE
Put grenades back.

### ISSUE THREAD

**Issue by kindaro** [fishfight/FishFight#98]
Grenades were added in #7. They were later removed, but I am going to put them back, fresh and juicy.

**Comment by kindaro** [comment]
Waiting for #113.

**Comment by erlend-sh** [comment]
Whoops, it appears we lost track of who was doing grenades, as it got done in #114. How about you do a mod of grenades instead?

https://steamcommunity.com/sharedfiles/filedetails/?id=491555785

Maybe a grenade that explodes with musket shots in all directions?

**Comment by kindaro** [comment]
I noticed. I am reluctant to close this ticket yet because I hope to eventually integrate #113 into grenades, in the spirit of #116. I am currently writing mines for #99 based on that draft.

**Comment by grufkork** [comment]
The grenades do not currently utilise the explosive struct, so that's something to do as well. Also if you want to add chain reactions to explosives in the same go, might as well!

**Comment by kindaro** [comment]
Noted in #137.

**Comment by olefasting** [comment]
Grenades are back, so I'm closing this
