### ISSUE TITLE
Put mines back.

### ISSUE THREAD

**Issue by kindaro** [fishfight/FishFight#99]
Mines were added in #8. They were later removed, but I am going to put them back, as fatal and insidious as ever.

* [ ] Adjustable trigger delay.
* [x]  Trigger radius independent of explosion radius.
  * [ ] Trigger radius larger than explosion radius?
* [ ] Explosions trigger mines in their radius?

**Comment by grufkork** [comment]
I am currently working on reimplementing the cannon and cannonball, as well as the actual hit detection to the explosion function. Unless you are really feeling like adding back the circle and related, I am currently working on it so you could just for the moment use the explosion function in utils.rs? It's only visual at the moment.

**Comment by kindaro** [comment]
Sure, thanks for letting me know. I see you have #92 in works.

**Comment by grufkork** [comment]
Alright, I got the explosions working again, so just make sure the particles go in the right place! My new code will have a function for returning all players intersecting a circle which could be useful, but it might just be better and more performant to do a distance check instead. By the way, are you in the discord? I couldn't find you there.

**Comment by kindaro** [comment]
Yes — I am not an especially real time person though.

**Comment by kindaro** [comment]
Waiting for #113.

**Comment by kindaro** [comment]
Trigger delay needs to be put into #113. We can talk about it once it is merged.
